#!/bin/bash
# Quick Setup Guide - Run this for complete installation

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║         IRS Database Server Setup - Quick Guide             ║"
echo "╔══════════════════════════════════════════════════════════════╗"
echo ""
echo "📋 STEP 1: Install Java, Maven, Docker & PostgreSQL"
echo "   Command: ./setup-docker-postgres.sh"
echo ""
echo "   What it does:"
echo "   ✓ Checks and installs Java 17 (OpenJDK)"
echo "   ✓ Checks and installs Maven"
echo "   ✓ Checks and installs Docker"
echo "   ✓ Pulls PostgreSQL 17 with PostGIS 3.4"
echo "   ✓ Creates container 'postgres-irs'"
echo "   ✓ Configures database 'irs'"
echo ""
echo "───────────────────────────────────────────────────────────────"
echo ""
echo "📋 STEP 2: Create Schema & Import Data"
echo "   Command: ./setup-database.sh"
echo ""
echo "   What it does:"
echo "   ✓ Shows all paths for verification"
echo "   ✓ Creates database schema (users, roles, accident reports, etc.)"
echo "   ✓ Inserts initial data"
echo "   ✓ Automatically imports ALL CSV files from the CSV directory"
echo ""
echo "───────────────────────────────────────────────────────────────"
echo ""
echo "🔧 PATH CONFIGURATION (in setup-database.sh)"
echo ""
echo "   BASE_DIR:         Auto-detected project root"
echo "   PROJECT_SQL_DIR:  src/main/resources/script_queries"
echo "   PROJECT_CSV_DIR:  src/main/resources/files (all .csv files)"
echo ""
echo "───────────────────────────────────────────────────────────────"
echo ""
echo "⚙️  DATABASE CONFIGURATION"
echo ""
echo "   Host:     0.0.0.0 (localhost)"
echo "   Port:     5432"
echo "   Database: irs"
echo "   Username: postgres"
echo "   Password: admin123/?"
echo ""
echo "   JDBC URL: jdbc:postgresql://localhost:5432/irs"
echo ""
echo "───────────────────────────────────────────────────────────────"
echo ""
echo "✅ KEY FEATURES"
echo ""
echo "   ✓ Scripts are IDEMPOTENT (safe to run multiple times)"
echo "   ✓ Tables use CREATE IF NOT EXISTS"
echo "   ✓ Data uses ON CONFLICT DO NOTHING"
echo "   ✓ Path validation before execution"
echo "   ✓ No data loss on re-run"
echo ""
echo "───────────────────────────────────────────────────────────────"
echo ""
echo "🚀 QUICK START"
echo ""
echo "   # Make scripts executable"
echo "   chmod +x setup-docker-postgres.sh setup-database.sh"
echo ""
echo "   # Install Java, Maven, Docker & PostgreSQL"
echo "   ./setup-docker-postgres.sh"
echo ""
echo "   # Create database schema and import data"
echo "   ./setup-database.sh"
echo ""
echo "   # Start your Quarkus app"
echo "   ./mvnw quarkus:dev"
echo ""
echo "───────────────────────────────────────────────────────────────"
echo ""
echo "🛠️  USEFUL COMMANDS"
echo ""
echo "   # Check container status"
echo "   docker ps | grep postgres-irs"
echo ""
echo "   # Connect to database"
echo "   docker exec -it postgres-irs psql -U postgres -d irs"
echo ""
echo "   # View container logs"
echo "   docker logs postgres-irs"
echo ""
echo "   # Start/Stop container"
echo "   docker start postgres-irs"
echo "   docker stop postgres-irs"
echo ""
echo "───────────────────────────────────────────────────────────────"
echo ""
echo "❓ TROUBLESHOOTING"
echo ""
echo "   Path not found?"
echo "   → Check paths in setup-database.sh (lines 22-28)"
echo ""
echo "   Container already exists?"
echo "   → Script will detect and ask to recreate or keep"
echo ""
echo "   Table already exists error?"
echo "   → Safe to ignore - using IF NOT EXISTS"
echo ""
echo "   CSV import fails?"
echo "   → Verify CSV file exists at specified path"
echo ""
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

read -p "Press Enter to continue..."
